# Generated by Django 2.0.13 on 2023-01-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230108_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tect',
            new_name='text',
        ),
    ]
